# 1. Set a common base
FROM tinygo/tinygo:0.27.0

# 2. Set required CNB information
ENV CNB_USER_ID=1000
ENV CNB_GROUP_ID=1000
ENV CNB_STACK_ID="net.aslom.wasm.wagi"
LABEL io.buildpacks.stack.id="net.aslom.wasm.wagi"

# 3. Create the user
# RUN groupadd cnb --gid ${CNB_GROUP_ID} && \
#   useradd --uid ${CNB_USER_ID} --gid ${CNB_GROUP_ID} -m -s /bin/bash cnb

# # 4. Install common packages
# RUN apt-get update && \
#   apt-get install -y xz-utils ca-certificates && \
#   rm -rf /var/lib/apt/lists/*

# 5. Start a new run stage
#FROM base as run

# # 8. Install packages that we want to make available at build time
# RUN apt-get update && \
#   apt-get install -y git wget jq && \
#   rm -rf /var/lib/apt/lists/* && \
#   wget https://github.com/tinygo-org/tinygo/releases/download/v0.27.0/tinygo_0.27.0_amd64.deb && \
#   sudo dpkg -i tinygo_0.27.0_amd64.deb

#COPY --from=run /usr/local/bin/wagi /usr/local/bin/wagi

# ========== ADDED ===========
# 9. Set user and group (as declared in base image)
USER ${CNB_USER_ID}:${CNB_GROUP_ID}
#CMD [ "wagi", "-l", "0.0.0.0:8080", "-c", "/modules.toml" ]
